SELECT 
    FLIGHT_ID,
    FLIGHT_NUMBER,
    AIRCRAFT_NUMBER,
    DEPARTURE_AIRPORT,
    ARRIVAL_AIRPORT,
    DATEDIFF('minute', ARRIVAL_TIME, DEPARTURE_TIME) AS FLIGHT_DURATION
FROM
    {{ ref('stg_flight') }}
WHERE DATEDIFF('minute', ARRIVAL_TIME, DEPARTURE_TIME) > 0


