WITH FLIGHT AS(
SELECT 
    fl.FLIGHT_ID AS FLIGHT_ID,
    fl.FLIGHT_NUMBER,
    CASE 
        WHEN fl.DEPARTURE_AIRPORT = '0' THEN 'OKV'
        ELSE fl.DEPARTURE_AIRPORT
        END AS DEPARTURE_AIRPORT,
    CASE 
        WHEN fl.ARRIVAL_AIRPORT = '0' THEN 'OKV'
        ELSE fl.ARRIVAL_AIRPORT
        END AS ARRIVAL_AIRPORT,
    fl.DEPARTURE_TIME,
    fl.ARRIVAL_TIME,
    ac.FLIGHT_NUMBER AS AIRCRAFT_NUMBER
FROM
    {{ source('RAW_LOCAL', 'FLIGHT_DATA') }} fl
LEFT JOIN {{ source('RAW_LOCAL', 'AIRCRAFT_DATA') }} ac ON fl.FLIGHT_ID = ac.AIRCRAFT_ID
)
SELECT * FROM FLIGHT